version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  mongo-express:
    image: "mongo-express:latest"
    ports:
      - "8081:8081"
  server:
    build : 
      dockerfile : Dockerfile
      context : .
    volumes :
      - /app/node_modules
      - .:/app
    ports:
      - "3000:3000"
